// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: matchmaking.proto

package matchmaking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*QueueStatus_QueueJoined
	//	*QueueStatus_WaitQueueJoined
	//	*QueueStatus_PromotedToQueue
	//	*QueueStatus_MatchFound
	//	*QueueStatus_QueueError
	Payload       isQueueStatus_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatus) Reset() {
	*x = QueueStatus{}
	mi := &file_matchmaking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatus) ProtoMessage() {}

func (x *QueueStatus) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatus.ProtoReflect.Descriptor instead.
func (*QueueStatus) Descriptor() ([]byte, []int) {
	return file_matchmaking_proto_rawDescGZIP(), []int{0}
}

func (x *QueueStatus) GetPayload() isQueueStatus_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueueStatus) GetQueueJoined() *QueueJoined {
	if x != nil {
		if x, ok := x.Payload.(*QueueStatus_QueueJoined); ok {
			return x.QueueJoined
		}
	}
	return nil
}

func (x *QueueStatus) GetWaitQueueJoined() *WaitQueueJoined {
	if x != nil {
		if x, ok := x.Payload.(*QueueStatus_WaitQueueJoined); ok {
			return x.WaitQueueJoined
		}
	}
	return nil
}

func (x *QueueStatus) GetPromotedToQueue() *PromotedToQueue {
	if x != nil {
		if x, ok := x.Payload.(*QueueStatus_PromotedToQueue); ok {
			return x.PromotedToQueue
		}
	}
	return nil
}

func (x *QueueStatus) GetMatchFound() *MatchFound {
	if x != nil {
		if x, ok := x.Payload.(*QueueStatus_MatchFound); ok {
			return x.MatchFound
		}
	}
	return nil
}

func (x *QueueStatus) GetQueueError() *QueueError {
	if x != nil {
		if x, ok := x.Payload.(*QueueStatus_QueueError); ok {
			return x.QueueError
		}
	}
	return nil
}

type isQueueStatus_Payload interface {
	isQueueStatus_Payload()
}

type QueueStatus_QueueJoined struct {
	QueueJoined *QueueJoined `protobuf:"bytes,1,opt,name=queue_joined,json=queueJoined,proto3,oneof"`
}

type QueueStatus_WaitQueueJoined struct {
	WaitQueueJoined *WaitQueueJoined `protobuf:"bytes,2,opt,name=wait_queue_joined,json=waitQueueJoined,proto3,oneof"`
}

type QueueStatus_PromotedToQueue struct {
	PromotedToQueue *PromotedToQueue `protobuf:"bytes,3,opt,name=promoted_to_queue,json=promotedToQueue,proto3,oneof"`
}

type QueueStatus_MatchFound struct {
	MatchFound *MatchFound `protobuf:"bytes,4,opt,name=match_found,json=matchFound,proto3,oneof"`
}

type QueueStatus_QueueError struct {
	QueueError *QueueError `protobuf:"bytes,5,opt,name=queue_error,json=queueError,proto3,oneof"`
}

func (*QueueStatus_QueueJoined) isQueueStatus_Payload() {}

func (*QueueStatus_WaitQueueJoined) isQueueStatus_Payload() {}

func (*QueueStatus_PromotedToQueue) isQueueStatus_Payload() {}

func (*QueueStatus_MatchFound) isQueueStatus_Payload() {}

func (*QueueStatus_QueueError) isQueueStatus_Payload() {}

type QueueJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueJoined) Reset() {
	*x = QueueJoined{}
	mi := &file_matchmaking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueJoined) ProtoMessage() {}

func (x *QueueJoined) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueJoined.ProtoReflect.Descriptor instead.
func (*QueueJoined) Descriptor() ([]byte, []int) {
	return file_matchmaking_proto_rawDescGZIP(), []int{1}
}

func (x *QueueJoined) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WaitQueueJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitQueueJoined) Reset() {
	*x = WaitQueueJoined{}
	mi := &file_matchmaking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitQueueJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitQueueJoined) ProtoMessage() {}

func (x *WaitQueueJoined) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitQueueJoined.ProtoReflect.Descriptor instead.
func (*WaitQueueJoined) Descriptor() ([]byte, []int) {
	return file_matchmaking_proto_rawDescGZIP(), []int{2}
}

func (x *WaitQueueJoined) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PromotedToQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotedToQueue) Reset() {
	*x = PromotedToQueue{}
	mi := &file_matchmaking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotedToQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotedToQueue) ProtoMessage() {}

func (x *PromotedToQueue) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotedToQueue.ProtoReflect.Descriptor instead.
func (*PromotedToQueue) Descriptor() ([]byte, []int) {
	return file_matchmaking_proto_rawDescGZIP(), []int{3}
}

func (x *PromotedToQueue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MatchFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Players       int32                  `protobuf:"varint,2,opt,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	mi := &file_matchmaking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_matchmaking_proto_rawDescGZIP(), []int{4}
}

func (x *MatchFound) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchFound) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

type QueueError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueError) Reset() {
	*x = QueueError{}
	mi := &file_matchmaking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueError) ProtoMessage() {}

func (x *QueueError) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueError.ProtoReflect.Descriptor instead.
func (*QueueError) Descriptor() ([]byte, []int) {
	return file_matchmaking_proto_rawDescGZIP(), []int{5}
}

func (x *QueueError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_matchmaking_proto protoreflect.FileDescriptor

const file_matchmaking_proto_rawDesc = "" +
	"\n" +
	"\x11matchmaking.proto\x12\vmatchmaking\"\xe7\x02\n" +
	"\vQueueStatus\x12=\n" +
	"\fqueue_joined\x18\x01 \x01(\v2\x18.matchmaking.QueueJoinedH\x00R\vqueueJoined\x12J\n" +
	"\x11wait_queue_joined\x18\x02 \x01(\v2\x1c.matchmaking.WaitQueueJoinedH\x00R\x0fwaitQueueJoined\x12J\n" +
	"\x11promoted_to_queue\x18\x03 \x01(\v2\x1c.matchmaking.PromotedToQueueH\x00R\x0fpromotedToQueue\x12:\n" +
	"\vmatch_found\x18\x04 \x01(\v2\x17.matchmaking.MatchFoundH\x00R\n" +
	"matchFound\x12:\n" +
	"\vqueue_error\x18\x05 \x01(\v2\x17.matchmaking.QueueErrorH\x00R\n" +
	"queueErrorB\t\n" +
	"\apayload\"'\n" +
	"\vQueueJoined\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x0fWaitQueueJoined\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x0fPromotedToQueue\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"?\n" +
	"\n" +
	"MatchFound\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\aplayers\x18\x02 \x01(\x05R\aplayers\"&\n" +
	"\n" +
	"QueueError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB7Z5github.com/catalinfl/adler/matchmaking/pb;matchmakingb\x06proto3"

var (
	file_matchmaking_proto_rawDescOnce sync.Once
	file_matchmaking_proto_rawDescData []byte
)

func file_matchmaking_proto_rawDescGZIP() []byte {
	file_matchmaking_proto_rawDescOnce.Do(func() {
		file_matchmaking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchmaking_proto_rawDesc), len(file_matchmaking_proto_rawDesc)))
	})
	return file_matchmaking_proto_rawDescData
}

var file_matchmaking_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_matchmaking_proto_goTypes = []any{
	(*QueueStatus)(nil),     // 0: matchmaking.QueueStatus
	(*QueueJoined)(nil),     // 1: matchmaking.QueueJoined
	(*WaitQueueJoined)(nil), // 2: matchmaking.WaitQueueJoined
	(*PromotedToQueue)(nil), // 3: matchmaking.PromotedToQueue
	(*MatchFound)(nil),      // 4: matchmaking.MatchFound
	(*QueueError)(nil),      // 5: matchmaking.QueueError
}
var file_matchmaking_proto_depIdxs = []int32{
	1, // 0: matchmaking.QueueStatus.queue_joined:type_name -> matchmaking.QueueJoined
	2, // 1: matchmaking.QueueStatus.wait_queue_joined:type_name -> matchmaking.WaitQueueJoined
	3, // 2: matchmaking.QueueStatus.promoted_to_queue:type_name -> matchmaking.PromotedToQueue
	4, // 3: matchmaking.QueueStatus.match_found:type_name -> matchmaking.MatchFound
	5, // 4: matchmaking.QueueStatus.queue_error:type_name -> matchmaking.QueueError
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_matchmaking_proto_init() }
func file_matchmaking_proto_init() {
	if File_matchmaking_proto != nil {
		return
	}
	file_matchmaking_proto_msgTypes[0].OneofWrappers = []any{
		(*QueueStatus_QueueJoined)(nil),
		(*QueueStatus_WaitQueueJoined)(nil),
		(*QueueStatus_PromotedToQueue)(nil),
		(*QueueStatus_MatchFound)(nil),
		(*QueueStatus_QueueError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchmaking_proto_rawDesc), len(file_matchmaking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchmaking_proto_goTypes,
		DependencyIndexes: file_matchmaking_proto_depIdxs,
		MessageInfos:      file_matchmaking_proto_msgTypes,
	}.Build()
	File_matchmaking_proto = out.File
	file_matchmaking_proto_goTypes = nil
	file_matchmaking_proto_depIdxs = nil
}
